version: "3.9"

services:
  api:
    image: yesha999/wikiandtranslationinone:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      API_ID: $API_ID
      API_HASH: $API_ID
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - 8443:8443
    volumes:
      - ./.env:/app/.env